In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_json('purchase_data.json')

In [3]:
ages = [0, 9.90, 14.90, 19.90, 24.9, 29.9, 34.90, 39.90, 9999999]
age_groups = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", ">40"]

In [4]:
df['Age Groups'] = pd.cut(df["Age"], ages, labels=age_groups)

In [5]:
df.head()

,Age,Gender,Item ID,Item Name,Price,SN,Age Groups
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34,35-39
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46,20-24
2,34,Male,174,Primitive Blade,2.46,Assastnya25,30-34
3,21,Male,92,Final Critic,1.36,Pheusrical25,20-24
4,23,Male,63,Stormfury Mace,1.27,Aela59,20-24

In [6]:
num_of_people = df['SN'].nunique()

In [7]:
count = pd.DataFrame({"Total Players": [num_of_people]})

## Player Count

In [8]:
count

   Total Players
0            573

In [9]:
total_items = df["Item ID"].nunique()
avg_price = df["Price"].mean()
total_rev = df["Price"].sum()
num_purchases = df["Price"].count()

In [10]:
purchase_summary_df = pd.DataFrame({"Number of Unique Items": [total_items],
                                    "Average Price": [avg_price],
                                    "Total Revenue": [total_rev],
                                    "Number of Purchases": [num_purchases]})

## Purchasing Analysis (Total)

In [11]:
purchase_summary_df

   Average Price  Number of Purchases  Number of Unique Items  Total Revenue
0       2.931192                  780                     183        2286.33

In [12]:
gender_demographics = df["Gender"].value_counts()

In [13]:
gender_demographics

Male                     633
Female                   136
Other / Non-Disclosed     11
Name: Gender, dtype: int64

In [14]:
gender_demographics / df["Gender"].count() * 100

Male                     81.153846
Female                   17.435897
Other / Non-Disclosed     1.410256
Name: Gender, dtype: float64

In [15]:
filtered_df = df.drop_duplicates("SN")

In [16]:
filtered_df

,Age,Gender,Item ID,Item Name,Price,SN,Age Groups
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34,35-39
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46,20-24
2,34,Male,174,Primitive Blade,2.46,Assastnya25,30-34
3,21,Male,92,Final Critic,1.36,Pheusrical25,20-24
4,23,Male,63,Stormfury Mace,1.27,Aela59,20-24
5,20,Male,10,Sleepwalker,1.73,Tanimnya91,20-24
6,20,Male,153,Mercenary Sabre,4.57,Undjaskla97,20-24
7,29,Female,169,"Interrogator, Blood Blade of the Queen",3.32,Iathenudil29,25-29
8,25,Male,118,"Ghost Reaver, Longsword of Magic",2.77,Sondenasta63,25-29
9,31,Male,99,"Expiration, Warscythe Of Lost Worlds",4.53,Hilaerin92,30-34
10,24,Male,57,"Despair, Favor of Due Diligence",3.81,Chamosia29,20-24
11,20,Male,47,"Alpha, Reach of Ending Hope",1.55,Sally64,20-24
12,30,Male,81,Dreamkiss,4.06,Iskossa88,30-34
13,23,Male,77,"Piety, Guardian of Riddles",3.68,Seorithstilis90,20-24
14,40,Male,44,Bonecarvin Battle Axe,2.46,Sundast29,>40
15,21,Male,96,Blood-Forged Skeletal Spine,4.77,Haellysu29,20-24
16,22,Female,123,Twilight's Carver,1.14,Sundista85,20-24
17,22,Female,59,"Lightning, Etcher of the King",1.65,Aenarap34,20-24
18,28,Male,91,Celeste,3.71,Iskista88,25-29
19,31,Male,177,"Winterthorn, Defender of Shifting Worlds",4.89,Assossa43,30-34
20,24,Male,78,"Glimmer, Ender of the Moon",2.33,Irith83,20-24
21,15,Male,3,Phantomlight,1.79,Iaralrgue74,15-19
22,11,Female,11,Brimstone,2.52,Deural48,10-14
23,19,Male,183,Dragon's Greatsword,2.36,Chanosia65,15-19
24,11,Male,65,Conqueror Adamantite Mace,1.96,Qarwen67,10-14
25,21,Male,63,Stormfury Mace,1.27,Idai61,20-24
26,29,Male,132,Persuasion,3.90,Aerithllora36,25-29
28,15,Male,49,"The Oculus, Token of Lost Worlds",4.23,Ilariarin45,15-19
29,16,Female,45,Glinting Glass Edge,2.46,Phaedai25,15-19
30,21,Female,155,War-Forged Gold Deflector,3.73,Eulaeria40,20-24
...,...,...,...,...,...,...,...
729,16,Male,134,Undead Crusader,4.67,Iskichinya81,15-19
730,10,Female,148,"Warmonger, Gift of Suffering's End",3.96,Hiadanurin36,10-14
731,20,Female,106,Crying Steel Sickle,2.29,Tyaelly53,20-24
732,23,Female,37,"Shadow Strike, Glory of Ending Hope",1.93,Shidai42,20-24
733,16,Male,8,"Purgatory, Gem of Regret",3.91,Bartassaya73,15-19
734,13,Male,175,Woeful Adamantite Claymore,1.24,Mindosiasya28,10-14
736,19,Male,45,Glinting Glass Edge,2.46,Indirrian56,15-19
737,22,Male,101,Final Critic,4.62,Sondim68,20-24
739,35,Female,93,Apocalyptic Battlescythe,3.91,Cosadar58,35-39
741,24,Male,145,Fiery Glass Crusader,4.45,Leyirra83,20-24
742,26,Male,84,Arcane Gem,2.23,Inguron55,25-29
746,35,Male,34,Retribution Axe,4.14,Ralasti48,35-39
747,32,Male,52,Hatred,4.39,Lamon28,30-34
748,15,Male,120,Agatha,1.91,Isri49,15-19
750,23,Male,86,Stormfury Lantern,1.28,Eollym91,20-24
752,15,Female,116,Renewed Skeletal Katana,2.37,Yalostiphos68,15-19
755,22,Female,179,"Wolf, Promise of the Moonwalker",1.88,Ailaesuir66,20-24
756,22,Male,6,Rusty Skull,1.20,Siasri67,20-24
758,20,Male,122,Unending Tyranny,1.21,Ryastycal90,20-24
761,28,Male,175,Woeful Adamantite Claymore,1.24,Raeduerin33,25-29
764,25,Male,70,Hope's End,3.89,Assassasda84,25-29
766,22,Female,84,Arcane Gem,2.23,Nitherian58,20-24
768,21,Male,158,"Darkheart, Butcher of the Champion",3.56,Chamucosda93,20-24
769,24,Male,73,Ritual Mace,3.74,Frichilsasya78,20-24
770,22,Male,141,Persuasion,3.27,Aenasu69,20-24
771,24,Male,25,Hero Cane,1.03,Lassista97,20-24
772,15,Male,31,Trickster,2.07,Sidap51,15-19
773,21,Male,44,Bonecarvin Battle Axe,2.46,Chamadarsda63,20-24
778,20,Male,75,Brutality Ivory Warmace,1.72,Quelaton80,20-24
779,23,Female,107,"Splitter, Foe Of Subtlety",3.61,Alim85,20-24

In [17]:
gender_demographics_perc = filtered_df["Gender"].value_counts() / filtered_df["Gender"].count() * 100

In [18]:
gender_demographics_perc

Male                     81.151832
Female                   17.452007
Other / Non-Disclosed     1.396161
Name: Gender, dtype: float64

In [19]:
total_counts = filtered_df["Gender"].value_counts()

In [20]:
total_counts

Male                     465
Female                   100
Other / Non-Disclosed      8
Name: Gender, dtype: int64

## Gender Demographics

In [21]:
gender_df = pd.DataFrame({"Percentage of Players": gender_demographics_perc,
                          "Total Count": total_counts})

In [22]:
gender_df

                       Percentage of Players  Total Count
Male                               81.151832          465
Female                             17.452007          100
Other / Non-Disclosed               1.396161            8

## Purchasing Analysis (Gender)

In [23]:
gender_purchase_total = df.groupby(["Gender"]).sum()["Price"].rename("Total Purchase Value")
gender_average = df.groupby(["Gender"]).mean()["Price"].rename("Average Purchase Value")
gender_counts = df.groupby(["Gender"]).count()["Price"].rename("Purchase Count")

normalized_total = gender_purchase_total / gender_df["Total Count"]

gender_data = pd.DataFrame({"Normalized Total": normalized_total, 
                            "Purchase Count": gender_counts, 
                            "Total Purchase Value": gender_purchase_total, 
                            "Average Purchase Value": gender_average})

gender_data = gender_data.loc[:, ["Purchase Count", "Average Purchase Value",
                                      "Total Purchase Value", "Normalized Total"]]

gender_data

,Purchase Count,Average Purchase Value,Total Purchase Value,Normalized Total
Gender,,,,
Female,136,2.815515,382.91,3.829100
Male,633,2.950521,1867.68,4.016516
Other / Non-Disclosed,11,3.249091,35.74,4.467500

In [24]:
ages = [0, 9.90, 14.90, 19.90, 24.9, 29.9, 34.90, 39.90, 9999999]
age_groups = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", ">40"]

In [25]:
filtered_df['Age Groups'] = pd.cut(filtered_df["Age"], ages, labels=age_groups)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [26]:
#group_names

In [27]:
filtered_df

,Age,Gender,Item ID,Item Name,Price,SN,Age Groups
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34,35-39
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46,20-24
2,34,Male,174,Primitive Blade,2.46,Assastnya25,30-34
3,21,Male,92,Final Critic,1.36,Pheusrical25,20-24
4,23,Male,63,Stormfury Mace,1.27,Aela59,20-24
5,20,Male,10,Sleepwalker,1.73,Tanimnya91,20-24
6,20,Male,153,Mercenary Sabre,4.57,Undjaskla97,20-24
7,29,Female,169,"Interrogator, Blood Blade of the Queen",3.32,Iathenudil29,25-29
8,25,Male,118,"Ghost Reaver, Longsword of Magic",2.77,Sondenasta63,25-29
9,31,Male,99,"Expiration, Warscythe Of Lost Worlds",4.53,Hilaerin92,30-34
10,24,Male,57,"Despair, Favor of Due Diligence",3.81,Chamosia29,20-24
11,20,Male,47,"Alpha, Reach of Ending Hope",1.55,Sally64,20-24
12,30,Male,81,Dreamkiss,4.06,Iskossa88,30-34
13,23,Male,77,"Piety, Guardian of Riddles",3.68,Seorithstilis90,20-24
14,40,Male,44,Bonecarvin Battle Axe,2.46,Sundast29,>40
15,21,Male,96,Blood-Forged Skeletal Spine,4.77,Haellysu29,20-24
16,22,Female,123,Twilight's Carver,1.14,Sundista85,20-24
17,22,Female,59,"Lightning, Etcher of the King",1.65,Aenarap34,20-24
18,28,Male,91,Celeste,3.71,Iskista88,25-29
19,31,Male,177,"Winterthorn, Defender of Shifting Worlds",4.89,Assossa43,30-34
20,24,Male,78,"Glimmer, Ender of the Moon",2.33,Irith83,20-24
21,15,Male,3,Phantomlight,1.79,Iaralrgue74,15-19
22,11,Female,11,Brimstone,2.52,Deural48,10-14
23,19,Male,183,Dragon's Greatsword,2.36,Chanosia65,15-19
24,11,Male,65,Conqueror Adamantite Mace,1.96,Qarwen67,10-14
25,21,Male,63,Stormfury Mace,1.27,Idai61,20-24
26,29,Male,132,Persuasion,3.90,Aerithllora36,25-29
28,15,Male,49,"The Oculus, Token of Lost Worlds",4.23,Ilariarin45,15-19
29,16,Female,45,Glinting Glass Edge,2.46,Phaedai25,15-19
30,21,Female,155,War-Forged Gold Deflector,3.73,Eulaeria40,20-24
...,...,...,...,...,...,...,...
729,16,Male,134,Undead Crusader,4.67,Iskichinya81,15-19
730,10,Female,148,"Warmonger, Gift of Suffering's End",3.96,Hiadanurin36,10-14
731,20,Female,106,Crying Steel Sickle,2.29,Tyaelly53,20-24
732,23,Female,37,"Shadow Strike, Glory of Ending Hope",1.93,Shidai42,20-24
733,16,Male,8,"Purgatory, Gem of Regret",3.91,Bartassaya73,15-19
734,13,Male,175,Woeful Adamantite Claymore,1.24,Mindosiasya28,10-14
736,19,Male,45,Glinting Glass Edge,2.46,Indirrian56,15-19
737,22,Male,101,Final Critic,4.62,Sondim68,20-24
739,35,Female,93,Apocalyptic Battlescythe,3.91,Cosadar58,35-39
741,24,Male,145,Fiery Glass Crusader,4.45,Leyirra83,20-24
742,26,Male,84,Arcane Gem,2.23,Inguron55,25-29
746,35,Male,34,Retribution Axe,4.14,Ralasti48,35-39
747,32,Male,52,Hatred,4.39,Lamon28,30-34
748,15,Male,120,Agatha,1.91,Isri49,15-19
750,23,Male,86,Stormfury Lantern,1.28,Eollym91,20-24
752,15,Female,116,Renewed Skeletal Katana,2.37,Yalostiphos68,15-19
755,22,Female,179,"Wolf, Promise of the Moonwalker",1.88,Ailaesuir66,20-24
756,22,Male,6,Rusty Skull,1.20,Siasri67,20-24
758,20,Male,122,Unending Tyranny,1.21,Ryastycal90,20-24
761,28,Male,175,Woeful Adamantite Claymore,1.24,Raeduerin33,25-29
764,25,Male,70,Hope's End,3.89,Assassasda84,25-29
766,22,Female,84,Arcane Gem,2.23,Nitherian58,20-24
768,21,Male,158,"Darkheart, Butcher of the Champion",3.56,Chamucosda93,20-24
769,24,Male,73,Ritual Mace,3.74,Frichilsasya78,20-24
770,22,Male,141,Persuasion,3.27,Aenasu69,20-24
771,24,Male,25,Hero Cane,1.03,Lassista97,20-24
772,15,Male,31,Trickster,2.07,Sidap51,15-19
773,21,Male,44,Bonecarvin Battle Axe,2.46,Chamadarsda63,20-24
778,20,Male,75,Brutality Ivory Warmace,1.72,Quelaton80,20-24
779,23,Female,107,"Splitter, Foe Of Subtlety",3.61,Alim85,20-24

In [28]:
age_group_counts = filtered_df["Age Groups"].value_counts()

In [29]:
age_group_perc = filtered_df["Age Groups"].value_counts() / filtered_df['Age Groups'].count() *100

In [30]:
age_group_df = pd.DataFrame({"Percentage of Players" : age_group_perc, 
                             "Total Count" : age_group_counts})

In [31]:
age_group_df

       Percentage of Players  Total Count
20-24              45.200698          259
15-19              17.452007          100
25-29              15.183246           87
30-34               8.202443           47
35-39               4.712042           27
10-14               4.013962           23
<10                 3.315881           19
>40                 1.919721           11

## Purchasing Analysis (Age)

In [32]:
purch_count = df.groupby(['Age Groups']).count()[['Item ID']]

In [33]:
purch_avg = df.groupby(['Age Groups']).mean()[['Price']]

In [34]:
purch_price = df.groupby(['Age Groups']).sum()[['Price']]

In [35]:
purch_normal = filtered_df.groupby(['Age Groups']).sum()[['Price']]

In [36]:
purch_chart = pd.concat([purch_count, purch_avg, purch_price, purch_normal], axis=1)

In [37]:
purch_chart.columns = ['Purchase Count', 'Average Purchase Price', 'Total Puchase Value', 'Normalized Totals']
#df.columns = ['a', 'b']

In [38]:
purch_chart

,Purchase Count,Average Purchase Price,Total Puchase Value,Normalized Totals
Age Groups,,,,
<10,28,2.980714,83.46,59.45
10-14,35,2.770000,96.95,62.04
15-19,133,2.905414,386.42,289.88
20-24,336,2.913006,978.77,765.69
25-29,125,2.962640,370.33,263.53
30-34,64,3.082031,197.25,152.60
35-39,42,2.842857,119.40,78.65
>40,17,3.161765,53.75,34.25

## Top Spenders

In [39]:
user_total = df.groupby(["SN"]).sum()["Price"].rename("Total Purchase Value")
user_average = df.groupby(["SN"]).mean()["Price"].rename("Average Purchase Price")
user_count = df.groupby(["SN"]).count()["Price"].rename("Purchase Count")

user_data = pd.DataFrame({"Total Purchase Value": user_total,
                          "Average Purchase Price": user_average,
                          "Purchase Count": user_count})

user_data.sort_values("Total Purchase Value", ascending=False).head(5)

             Average Purchase Price  Purchase Count  Total Purchase Value
SN
Undirrala66                3.412000               5                 17.06
Saedue76                   3.390000               4                 13.56
Mindimnya67                3.185000               4                 12.74
Haellysu29                 4.243333               3                 12.73
Eoda93                     3.860000               3                 11.58

## Most Popular Items

In [40]:
item_total = df.groupby(["Item Name"]).sum()["Price"].rename("Total Purchase Value")
item_average = df.groupby(["Item Name"]).mean()["Price"].rename("Purchase Price")
item_count = df.groupby(["Item Name"]).count()["Price"].rename("Purchase Count")

item_data = pd.DataFrame({"Total Purchase Value": item_total,
                          "Purchase Price": item_average,
                          "Purchase Count": item_count})

item_data.sort_values("Purchase Count", ascending=False).head(5)

,Purchase Count,Purchase Price,Total Purchase Value
Item Name,,,
Final Critic,14,2.757143,38.60
Arcane Gem,11,2.230000,24.53
"Betrayal, Whisper of Grieving Widows",11,2.350000,25.85
Stormcaller,10,3.465000,34.65
Woeful Adamantite Claymore,9,1.240000,11.16

## Most Profitable Items

In [41]:
item_total = df.groupby(["Item Name"]).sum()["Price"].rename("Total Purchase Value")
item_average = df.groupby(["Item Name"]).mean()["Price"].rename("Purchase Price")
item_count = df.groupby(["Item Name"]).count()["Price"].rename("Purchase Count")

item_data = pd.DataFrame({"Total Purchase Value": item_total,
                          "Purchase Price": item_average,
                          "Purchase Count": item_count})

item_data.sort_values("Total Purchase Value", ascending=False).head(5)

,Purchase Count,Purchase Price,Total Purchase Value
Item Name,,,
Final Critic,14,2.757143,38.60
Retribution Axe,9,4.140000,37.26
Stormcaller,10,3.465000,34.65
Spectral Diamond Doomblade,7,4.250000,29.75
Orenmir,6,4.950000,29.70